### ISSUE TITLE
Source Separation .cfg files Target source doesn't work

### ISSUE THREAD

**Issue by kmads** [mcartwright/CAQE#4]
This may have to do with the fact that 'Reference' is used in the .cfg instead of 'Target'

**Comment by kmads** [comment]
In sourceseparation_pairwise.cfg and courceseparation_mushra.cfg, change 'Reference' in the `data` dictionary to 'Target'. This fixes the issue and allows the entire test to be taken without problems.

**Comment by mcartwright** [comment]
Fixed by 2b9e10e72ce8d508201c8a6d71d536bc63ad621d
